[project]
name = "backend"
version = "0.1.0"
description = "La langue au chat Game Session API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn[standard]"
]
